import type { Metadata } from "next";
import { Playfair_Display, Lora, Cormorant_Garamond, } from "next/font/google";
import "./globals.css";
import RootClient from "@/components/RootClient";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair",
});

const cormo = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-cormo"
})


const lora = Lora({
  subsets: ["latin"],
  weight: ["400","500","600","700"],
  variable: "--font-lora",
});

export const metadata: Metadata = {
  title: "The Wedding of Risma & Adam",
  description: "Generated by Pakdomm",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${lora.variable} ${cormo.variable} antialiased`}
      >
       <RootClient>{children}</RootClient>
      </body>
    </html>
  );
}
